# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-14 15:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DontSendEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_address', models.CharField(max_length=320)),
                ('when_added', models.DateTimeField()),
            ],
            options={
                'verbose_name': "don't send entry",
                'verbose_name_plural': "don't send entries",
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_address', models.CharField(max_length=320)),
                ('from_address', models.CharField(max_length=320)),
                ('subject', models.CharField(max_length=100)),
                ('message_body', models.TextField()),
                ('when_added', models.DateTimeField(default=datetime.datetime.now)),
                ('priority', models.CharField(choices=[(b'1', b'high'), (b'2', b'medium'), (b'3', b'low'), (b'4', b'deferred')], default=b'2', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_address', models.CharField(max_length=320)),
                ('from_address', models.CharField(max_length=320)),
                ('subject', models.CharField(max_length=100)),
                ('message_body', models.TextField()),
                ('when_added', models.DateTimeField()),
                ('priority', models.CharField(choices=[(b'1', b'high'), (b'2', b'medium'), (b'3', b'low'), (b'4', b'deferred')], max_length=1)),
                ('when_attempted', models.DateTimeField(default=datetime.datetime.now)),
                ('result', models.CharField(choices=[(b'1', b'success'), (b'2', b"don't send"), (b'3', b'failure')], max_length=1)),
                ('log_message', models.TextField()),
            ],
        ),
    ]
